skus:
  WL008:
    custo: 68.59
    peso: 1.0
    tipo_anuncio: Clássico
  WL009:
    custo: 71.38
    peso: 1.0
    tipo_anuncio: Clássico
  WL010:
    custo: 78.96
    peso: 0.5
    tipo_anuncio: Clássico
  WL013:
    custo: 43.11
    peso: 0.15
    tipo_anuncio: Clássico
  WL025:
    custo: 68.74
    peso: 1.0
    tipo_anuncio: Clássico
  WL028:
    custo: 82.26
    peso: 1.0
    tipo_anuncio: Clássico
  WL029:
    custo: 93.6
    peso: 0.5
    tipo_anuncio: Clássico
  WL033:
    custo: 60.74
    peso: 0.1
    tipo_anuncio: Clássico
  WL034:
    custo: 27.97
    peso: 0.1
    tipo_anuncio: Clássico
  WL035:
    custo: 60.24
    peso: 0.1
    tipo_anuncio: Clássico
  WL036:
    custo: 27.97
    peso: 0.1
    tipo_anuncio: Clássico
  WL039:
    custo: 82.42
    peso: 1.0
    tipo_anuncio: Clássico
  WL041:
    custo: 86.23
    peso: 1.0
    tipo_anuncio: Clássico
  WL043:
    custo: 86.36
    peso: 0.5
    tipo_anuncio: Clássico
  WLK004:
    custo: 142.5
    peso: 2.0
    tipo_anuncio: Clássico
  WLK005:
    custo: 147.55
    peso: 1.5
    tipo_anuncio: Clássico
  WLK006:
    custo: 218.0
    peso: 2.5
    tipo_anuncio: Clássico
  WLK018:
    custo: 168.65
    peso: 2.0
    tipo_anuncio: Clássico
  WLK019:
    custo: 168.78
    peso: 1.5
    tipo_anuncio: Clássico
  WLK020:
    custo: 255.01
    peso: 2.5
    tipo_anuncio: Clássico
  WLK026:
    custo: 176.86
    peso: 1.5
    tipo_anuncio: Clássico
  WLK047:
    custo: 182.49
    peso: 2.2
    tipo_anuncio: Clássico
  WLK169:
    custo: 164.51
    peso: 2.0
    tipo_anuncio: Clássico
  WLK249:
    custo: 142.5
    peso: 2.0
    tipo_anuncio: Clássico
